### ISSUE TITLE
cm-rgb-monitor fails with UnboundLocalError: local variable 'sensorIndex' referenced before assignment

### ISSUE THREAD

**Issue by dominalien** [gfduszynski/cm-rgb#60] opened 2022-02-18 09:40 UTC
For some time now I've been getting the error as per title when starting cm-rgb-monitor. This may be tied to upgrading the Pop_os I'm running to 21.04 or something thereabouts.

The command I'm using is:
`/home/domin/.local/bin/cm-rgb-monitor --cpu-color=#444499 --bg-color=#FFFFFF --show-temp --temp-low-color=#444444 --temp-high-color=#FF0000`

The output is:
`Traceback (most recent call last):
  File "/home/domin/.local/bin/cm-rgb-monitor", line 218, in <module>
    monitor()
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/domin/.local/bin/cm-rgb-monitor", line 156, in monitor
    t = psutil.sensors_temperatures()[sensorGroup][sensorIndex].current
UnboundLocalError: local variable 'sensorIndex' referenced before assignment`

cm-rgb is installed using pip. The version listed is 0.3.6. Removing --show-temp fixes the issue.

Any idea what may be wrong? If there's any more info I can provide pls let me know.

**Comment by gfduszynski** [comment] 2022-02-18 09:44
Looks like this can be caused by new ``click`` library version, could you try to downgrade to 7.1.2 and see if it helps ?

**Comment by dominalien** [comment] 2022-02-18 09:49
I am on 7.1.2. Exactly python3-click 7.1.2-1 (impish).

**Comment by gfduszynski** [comment] 2022-02-18 09:59
Ok, please try to run ``cm-rgb-monitor --list-temp-sources`` and paste the result

**Comment by dominalien** [comment] 2022-02-18 10:02
> Available sensors:
>nvme/Composite  ->  36.85
>nvme/Sensor 1  ->  36.85
>nvme/Sensor 2  ->  49.85
>nvme/Composite  ->  44.85
>k10temp/Tctl  ->  35.875
>k10temp/Tccd1  ->  38.5
>Available fan speed sensors for mirage:

**Comment by gfduszynski** [comment] 2022-02-18 10:04
Ok, thats the cause.
``@click.option("--temp-source", "tempSource", type=str, default="k10temp/Tdie", help="Temperature source <chip>/<feature> (eg. \"k10temp/Tdie\")")``

When no source is specified the default is ``k10temp/Tdie``, this one is not available on your system.

Try adding ``--temp-source=k10temp/Tctl`` to your command.

**Comment by gfduszynski** [comment] 2022-02-18 11:01
Let me know if this solves the problem so I can close the issue.

**Comment by dominalien** [comment] 2022-02-18 14:18
Yes, specifying temp-source fixes the error.

Thank you for your speedy responses, cm-rgb is very nice :-)

**Comment by gfduszynski** [comment] 2022-02-18 19:27
Thank you, means a lot :)

**Closed as completed by gfduszynski** 2022-02-18 19:27 UTC
